version: "2.3"
services:
  python:
#    image: tensorflow/tensorflow
    build: build/python
    container_name: first_ai_python
    volumes:
      - ./code:/var/www/html/
      - ./mysql/logs:/var/www/logs
    tty: true
    working_dir: /var/www/html
#    user: www-data
  mysql:
    image: mysql:latest
    container_name: first_ai_mysql
    volumes:
      - ./mysql:/var/lib/mysql:delegated
      - ./config/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "3306:3306"
    env_file:
      - ./config/mysql/mysql.env
